repos:
-   repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: "pip freeze > requirements.txt"
        language: system
        pass_filenames: false
        stages: [commit]

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: [--max-line-length=131]

-   repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
      - id: commitizen
  