version: '3.8'

services:

  postgresdb:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    volumes:
    - pgVolume:/var/lib/postgresql/data
    ports:
    - 5432:5432

  # users-api:
  #   build: 
  #     context: .
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - postgresdb

volumes:
  pgVolume:
